name: KaldenvoldPlugin
main: com.jamesmonger.kaldenvold.KaldenvoldPlugin
version: 0.9

commands:
   ooc:
      description: Global OOC chat toggle.
      usage: /<(o)oc>
   o:
      description: Global OOC chat toggle.
      usage: /<(o)oc>
   autotranslate:
      description: Super ears!
      usage: /autotranslate
   ability:
      description: Toggle your race ability.
      usage: /ability
   acceptplayer:
      description: Accept a player to Kaldenvold
      usage: /acceptplayer [player]