name: KaldenvoldPlugin
main: com.jamesmonger.kaldenvold.KaldenvoldPlugin
version: 0.9

commands:
   togglegooc:
      description: Toggle Global OOC.
      usage: /togglegooc
   me:
      description: Perform an action.
      usage: /me [action]
   ooc:
      description: Use /ch instead.
      usage: /ooc
   o:
      description: Use /ch instead.
      usage: /o
   channel:
      description: Change chat channel.
      usage: /<ch>annel [channel]
   ch:
      description: Change chat channel.
      usage: /<ch>annel [channel]
   autotranslate:
      description: Super ears!
      usage: /autotranslate
   ability:
      description: Toggle your race ability.
      usage: /ability
   acceptplayer:
      description: Accept a player to Kaldenvold
      usage: /acceptplayer [player]